USE [master]
GO

/****** Object:  Database [SWD2]    Script Date: 28.02.2023 20:18:33 ******/
CREATE DATABASE [SWD2]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'SWD2', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERIWAN\MSSQL\DATA\SWD2.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'SWD2_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVERIWAN\MSSQL\DATA\SWD2_log.ldf' , SIZE = 466944KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [SWD2].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [SWD2] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [SWD2] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [SWD2] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [SWD2] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [SWD2] SET ARITHABORT OFF 
GO

ALTER DATABASE [SWD2] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [SWD2] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [SWD2] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [SWD2] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [SWD2] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [SWD2] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [SWD2] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [SWD2] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [SWD2] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [SWD2] SET  DISABLE_BROKER 
GO

ALTER DATABASE [SWD2] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [SWD2] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [SWD2] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [SWD2] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [SWD2] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [SWD2] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [SWD2] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [SWD2] SET RECOVERY FULL 
GO

ALTER DATABASE [SWD2] SET  MULTI_USER 
GO

ALTER DATABASE [SWD2] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [SWD2] SET DB_CHAINING OFF 
GO

ALTER DATABASE [SWD2] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [SWD2] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [SWD2] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [SWD2] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [SWD2] SET QUERY_STORE = OFF
GO

ALTER DATABASE [SWD2] SET  READ_WRITE 
GO


